### ISSUE TITLE
This repository needs a license

### ISSUE THREAD

**Issue by mvdan** [Binject/debug#12]
Hi! @capnspacehook added this module as a dependency in https://github.com/burrowers/garble, which I think is perfectly reasonable.

Unfortunately, this repository has no license information, which is pretty scary. Please add some, which I assume should be just a copy of Go's own license info. With a license file, https://pkg.go.dev/github.com/Binject/debug/goobj2 would also work, which is now an error due to the lack of license info.

**Comment by capnspacehook** [comment]
Whoops, this repo was originally cloned copy of the stdlib debug package, so the license from Go was copied with it. Thanks for bringing this up!
