### ISSUE TITLE
how to deal with SectionHeader[i].VirtualAddress

### ISSUE THREAD

**Issue by timwhitez** [Binject/debug#23]
i want to change https://github.com/frkngksl/Huan/blob/7e533ceeeedeecf390546a077bca3400960f5a4a/HuanLoader/Loader.cpp
go golang.
bug i don't know how to deal with line 137-139.

**Comment by awgh** [comment]
@timwhitez Please check out our reference loader, Universal, which uses debug/pe to do exactly this:  https://github.com/Binject/universal/blob/main/loader_windows.go#L74

**Comment by timwhitez** [comment]
thanks!
