### ISSUE TITLE
DOS Stub incorrectly marked as not present

### ISSUE THREAD

**Issue by kulinacs** [Binject/debug#26]
https://github.com/Binject/debug/blob/9605c99179ee9bcf58d57878fbca1c0be63c7d4e/pe/file.go#L101

I noticed binject was nulling out the DOSStub when doing some static patching and narrowed it down to this branch -  I _believe_ the greater than check is just flipped (or maybe should be !=) but in either case, changing to 

`if dosHeaderSize < int(f.DosHeader.AddressOfNewExeHeader) {`

at least results in a PE generated with the stub properly.

**Comment by awgh** [comment]
Thanks!  After squinting at this for a bit, I think the greater than sign was also flipped.  I was able to verify that with this change the DOS Stub is not zeroed when binjecting a mingw-generated binary.  Marking this closed.  

https://github.com/Binject/debug/commit/febe44e5965e07e9e273719dd8474339a8eae889
