### ISSUE TITLE
pe Bytes() call has leftover debugging log

### ISSUE THREAD

**Issue by C-Sto** [Binject/debug#8]
As per title - looks like it just needs to be commented out.

https://github.com/Binject/debug/blob/3ba66a81a91c410fd4928f42e1bae704a7864bbc/pe/write.go#L86

**Comment by awgh** [comment]
Yup, also commented out all other debug prints except the overlapping sections warnings for macho & elf.  Would be nice to convert these to a logging scheme that does nothing by default, but has debug/warning/error levels and can write to a file instead.
